# Generated by Django 2.0.5 on 2018-05-22 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FavColor',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FavSong',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('friend_name', models.CharField(max_length=100)),
                ('friend_dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='m_color',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='m_food',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('food', models.CharField(max_length=150)),
                ('items', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='m_movie',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='m_song',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='m_workpalce',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ph_num', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='m_zodiac',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('sign', models.CharField(max_length=25, unique=True)),
                ('desc', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(null=True)),
                ('care_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.Member')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zodiac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.m_zodiac')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('reminder', models.TextField(max_length=1200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop1', models.CharField(blank=True, max_length=20)),
                ('stop2', models.CharField(blank=True, max_length=20)),
                ('avg_time', models.IntegerField()),
                ('time_today', models.IntegerField(blank=True)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.m_workpalce')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Member')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usermessage', models.TextField(max_length=10000)),
                ('computermessage', models.TextField(max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watched_Movie',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Member')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.m_movie')),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('wish', models.CharField(max_length=150)),
                ('priority', models.PositiveIntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Member')),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Member'),
        ),
        migrations.AddField(
            model_name='favsong',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Member'),
        ),
        migrations.AddField(
            model_name='favsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.m_song'),
        ),
        migrations.AddField(
            model_name='favcolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.m_color'),
        ),
        migrations.AddField(
            model_name='favcolor',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Member'),
        ),
        migrations.AddField(
            model_name='eat',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.m_food'),
        ),
        migrations.AddField(
            model_name='eat',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Member'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.Member'),
        ),
    ]
